config/routes.rb
Tweeter::Application.routes.draw do
  devise_for :users
  
  resources :tweets
  resources :users do
    member do
      post :follow
      delete :follow, :to => 'users#unfollow'
    end
  end
  


  root :to => 'tweets#index'
end

app/models/followers.rb
class Followers < ActiveRecord::Base
  self.table_name = 'users_followers'
  
  belongs_to :user
  belongs_to :followed, :class_name => 'User'
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :body
  belongs_to :user
  
  validates_presence_of :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets, :order => 'created_at DESC'
  has_and_belongs_to_many :followed, :class_name => 'User', :foreign_key => 'user_id', :association_foreign_key => 'followed_user_id'
#  has_and_belongs_to_many :following, :class_name => 'User', :foreign_key => 'user_id'
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :nickname
  # attr_accessible :title, :body
  
  validates_presence_of :nickname
  
  def followeds_tweets
    Tweet.find_by_sql(<<-SQL
    SELECT *
    FROM 
      tweets t
    WHERE
     t.user_id IN (SELECT followed_user_id FROM users_users WHERE user_id = #{id})
    SQL
    )
  end
  
  def news_feed
    followeds_tweets + tweets
  end
  
  def is_following?(compared_user)
    followed.include? compared_user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :get_current_user
  
  def get_current_user
    @current_user = current_user
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def index
#    @tweets = Tweet.all
    @tweets = 
      if current_user
        current_user.followeds_tweets
      else
        Tweet.limit(50).order('created_at DESC')
      end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(params[:tweet])

    @tweet.user = current_user

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet.user, notice: 'Tweet to Tweeter has been TWEETED!' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  # def update
  #   @tweet = Tweet.find(params[:id])
  # 
  #   respond_to do |format|
  #     if @tweet.update_attributes(params[:tweet])
  #       format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @tweet.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  def show
    @user = User.find(params[:id], :include => :tweets)
    @new_tweet = Tweet.new if @user == current_user
  end
  
  # POST /users/1/follow
  def follow
#    redirect_to '/' if params[:id].blank?
    puts params.inspect
    @user = User.find(params[:id])
    current_user.followed << @user
    redirect_to @user
  end
  
  # DELETE /users/1/follow
  def unfollow
    puts params.inspect
    @user = User.find(params[:id])
    current_user.followed.delete(@user)
    redirect_to @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tweeter" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Tweeter</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <% if @current_user %>
                <li><%= link_to "News Feed", "/"  %></li>
                <li><%= link_to "My Tweets", '/users/' + @current_user.id.to_s %></li>
                <li><%= link_to "Log Out", :destroy_user_session, :method => :delete  %></li>
                <li>Hey there, <%= @current_user.nickname %>!</li>
              <% else %>
                <li><%= link_to "Sign Up", "/users/sign_up"  %></li>
                <li><%= link_to "Log in", "/users/sign_in"  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12 body">
            <% if notice %>
              <p class="notice"><%= notice %></p>
            <% end %>
            <% if alert %>
              <p class="alert"><%= alert %></p>
            <% end %>
            
            <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Your Tweeter Feed</h1>
<% @tweets.each do |tweet| %>
<p>
  <%= tweet.body %>
  <br>
  -
  <%= link_to tweet.user.nickname, tweet.user %>
</p>
<% end %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @tweet.body %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/users/show.html.erb
<h1><%= @user.nickname %>'s Feed</h1>

<% if @current_user == @user %>
  <%= form_for @new_tweet do |f| %>
    <%= f.text_field :body %>
    
    <%= f.submit 'Tweet it!' %>
  <% end %>
<% end %>
<% unless @current_user == @user %>
  <% if current_user.is_following? @user %>
    <%= button_to "Unfollow #{@user.nickname}", user_follow_path(@user), :method => :delete %>
  <% else %>
    <%= button_to "Follow #{@user.nickname}", user_follow_path(@user), :method => :post %>
  <% end %>
<% end %>
<% @user.tweets.each do |tweet| %>
<p>
  <%= tweet.body %>
  <br>
  -
  <%= link_to tweet.user.nickname, tweet.user %>
</p>
<% end %>